### ISSUE TITLE
Mistakes in Lugbarati characters

### ISSUE THREAD

**Issue by espensj** [global-asp/asp-source#1]
Some of the Lugbarati (official) stories are rendered improperly – some diacritics don't appear.

https://github.com/global-asp/asp-source/blob/master/lgg-official/0009_ma_vile_busua_ngua_ya.md

![screen shot 2016-03-13 at 3 26 33 pm](https://cloud.githubusercontent.com/assets/12679303/13731807/002f2b54-e930-11e5-9a58-6eedb64f3c24.png)

**Comment by dohliam** [comment]
I found ten stories in Lugbarati affected by this problem:

* 0009_ma_vile_busua_ngua_ya.md
* 0030_afaamazu_0.md
* 0053_di_ma_i_1.md
* 0067_nyaka_adiza_3.md
* 0111_robi_yi_ma_biko_yo_adi_eyosia_ri_0.md
* 0206_si_3.md
* 0215_nyaka_obiti_siri_1.md
* 0231_buku_angu_mile_ni_ri_1.md
* 0241_drileonzi_2.md
* 0323_kaiko_engapi_engari.md

This is not due to conversion errors -- the problem exists in the original pdfs due to the font that was used. For example, you can see the problem in 0009 [here](https://drive.google.com/open?id=0B59ZADK9EsbsUHlUdlJpWW9fa0E).

All the original Lugbarati (official) pdfs are available [here](https://drive.google.com/folderview?id=0B59ZADK9EsbsWHdLN05NXzkwbjg&usp=sharing), so you can compare them to see that the text is not recoverable.

The only chance of getting the correct text is if the new ASP website has fixed the problem on their end. Even though the text cannot be selected, we can still (with some difficulty) retrieve it, so long as it is correct. I'll check this out ASAP.

**Comment by espensj** [comment]
Yes, I know the main website has some problems with this. Again, after 2
years this is really just ... let me save the adjective
E
