### ISSUE TITLE
Title broken: lgg-official/0004

### ISSUE THREAD

**Issue by espensj** [global-asp/asp-source#2]
https://github.com/global-asp/asp-source/blob/master/lgg-official/0004_ndri_i_oco_i_azini_ti_i_0.md

Now it's like this:
![screen shot 2016-03-13 at 3 41 52 pm](https://cloud.githubusercontent.com/assets/12679303/13731903/244a50b6-e932-11e5-88a7-6e7765bb376a.png)

It should be like this:

Title
![screen shot 2016-03-13 at 3 40 44 pm](https://cloud.githubusercontent.com/assets/12679303/13731896/03a2f606-e932-11e5-8578-888a6a331103.png)

First page
![screen shot 2016-03-13 at 3 40 52 pm](https://cloud.githubusercontent.com/assets/12679303/13731898/09b7cac6-e932-11e5-9f15-c831c9dc3966.png)

**Comment by dohliam** [comment]
Do you mean that the title should include both lines? If so, I can fix this easily

**Comment by espensj** [comment]
Yes.

E

**Comment by dohliam** [comment]
Fixed now. I also fixed several other Lugbarati titles that were broken due to the conversion from pdf:

* 0004_ndri_i_oco_i_azini_ti_i_0.md
* 0005_anikanika_pi_okuku_be_1.md
* 0039_agupi_oko_ri_pi_oku_oko_ri_be_1.md
* 0042_oboloko_abiri_ni_nde_ra_ri_pi_cucu_be._0.md
* 0078_idri_nyaza_ti_okpo_be_ri_ni_ri_2.md
* 0147_ma_i_azini_aku_ama_vile_ri_0.md
* 0158_au_pi_yuku_be_0.md
* 0169_ebioeji_bayini_adikoyiawaa_1.md
* 0312_ewamva_olukulua_be_ri_1.md
